# Generated by Django 5.2.16 on 2026-07-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_remove_usermodel_groups_remove_usermodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_insights',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
