# Generated by Django 5.2.16 on 2026-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_resume_resume_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_resume_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
