# Generated by Django 5.2.16 on 2026-07-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0007_resume_is_resume_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('employment_type', models.CharField(blank=True, default='', max_length=100)),
                ('work_mode', models.CharField(blank=True, default='', max_length=100)),
                ('experience', models.CharField(blank=True, default='', max_length=100)),
                ('posted_at', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('apply_link', models.URLField(blank=True, default='')),
                ('match_score', models.FloatField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='userside.usermodel')),
            ],
        ),
    ]
