# Generated by Django 5.1.2 on 2026-07-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0009_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ats_score', models.PositiveSmallIntegerField(default=0)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('career_roadmap', models.JSONField(blank=True, default=list)),
                ('learning_recommendations', models.JSONField(blank=True, default=list)),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('interview_questions', models.JSONField(blank=True, default=list)),
                ('job_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
